### ISSUE TITLE
Godot language support

### ISSUE THREAD

**Issue by ShalokShalom** [nonunknown/godot-powerful#2]
Hi friend 😄 

Your list contains some of the additional language bindings.

We already host and maintian such a list here, so if you wish, you can just link to it.

https://github.com/Vivraan/godot-lang-support

Much fun

**Comment by nonunknown** [comment]
you can make the modifications you think would improve the repo and make a PR at any time :D

**Comment by ShalokShalom** [comment]
yeah, but then we have to synchronize two repos at the time

**Comment by nonunknown** [comment]
you didnt got it, just change mine README to instead of list the Language section to a link to your repo, make these changes and PR I'll check and approve! if its well done of course!

**Comment by ShalokShalom** [comment]
Ah, ok.
